id = "github-dark-colorblind"
name = "GitHub Dark Colorblind"
version = "1.0.0"
schema_version = 1
authors = ["pyrxm"]
description = "A modified port of the GitHub VSCode theme for colorblind users."
repository = "https://github.com/pyrxm/zed-github-dark"
